luks_device:
  uuid: "bf292469-5933-4494-acb5-36a5e7319d5c"
  mountpoint: /media/sandisk

connection_name: "netplan-eth0"
connection_type: "ethernet"

nfs_exports:
  - path: "{{ luks_device.mountpoint }}"
    exposure: "{{ scale_netmask.v4 }}"
    options: "rw,sync,no_subtree_check,no_root_squash"
    local_mount: /mnt/nfs/media
    mount_opts: "rw,hard,intr,timeo=600,retrans=2,_netdev"
    group: nfs
    gid: 1000
    subdirs:
      - path: "{{ luks_device.mountpoint }}/persistent"
        group: persistent
        gid: 2000
      - path: "{{ luks_device.mountpoint }}/temp"
        group: temp
        gid: 2001

static_ip: 192.168.0.17
