apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wakapi
  namespace: wakapi
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`waka.scrimreaper.dev`)
      services:
        - kind: Service
          name: wakapi
          port: 3000
