# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: waka-password-salt
    namespace: wakapi
type: Opaque
stringData:
    password_salt: ENC[AES256_GCM,data:A2syUGaTKay3YcUyv84ZWs6JMikK74jSTHcQgOxZeUwk74uAqImKrvJTspkNuoZ1Rtwy082qcQg6+Z8IC2II+OFMyp7QBy9XglAPJH4TjKASiqiJQYMw/w==,iv:Ekc5dzYt3hhI0kELDFZjPd6k8k7WD7pD5wnUpug2E04=,tag:eaOqHk2NMkGHvJcHJL1UYw==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdUgrdkx1OXJGVVRFMlhW
            RTg2T3NjbzNqZHhONndDak5xajJBU2pBTG44ClpBWC9paSt0dTVmVFJuVGw4R0U1
            WlFadHJRYnYrN3I0TW55dklJejkyWGcKLS0tIDd2Z2o3N1V2REtjb2k0Yy9OdHVB
            S0sxK2EzQ2taMHl2M1A2djJmaDFWUE0KFikq8Wv1KfVSLNHKadCzFkKH1jl8xi49
            auSpXIZSLBbA0zaIkA2RPtRK5SEDnzTYMg/dTQCyreV/Q+JEh1fh3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:56:20Z"
    mac: ENC[AES256_GCM,data:iIa4ImUpWr1+V0GZrBPUBuQ5P8G469s64KF3TFVi12d8694W5INJQjRj2Cxsjnk97maG7BLzBZX7+osUNuaYPz396HjBQlIBxSsgaGJPWpE3YLlgPeb2T5Y8f+aKZdHEbkjwLxXejB0nqoDV0Rc8QeE9s5pK6NfotChHosddrLY=,iv:4sJnpRRE1SJ38caOJ+og3HZQp8JOZkI83Q9RcUu59fI=,tag:Q/0dn0diD0Ku43jyN+u4QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
