# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: waka-oidc-secret
    namespace: wakapi
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:tvGSzCzUuYEUvCOQ+dW7C5MmPTVuqPAhyO2Q3SvftY/g24sGPup/AmXkzLS4jUIHp3/s2flMCeVLd/A7nI9weQ==,iv:rY34uG8BtfypZT09wLYUc5VXGPTEq1S90pTAa4L4tww=,tag:kKOk4uhKo1fwDAunuy6CEw==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cTB2SnRtRjRkc2pXR21N
            Y3FGVndKeC9Nb3VjSjJpaVRKdHA3ZlpwNVdZCmNGKzE5ZmltN0JFRG1Bc1pBS2s0
            RmVhckxMb0dCemsyem9zdWZsc3NYYU0KLS0tIDUrMXJTbmQ0cjZ4N2NxeXlMNWpm
            VFVhSFB3YjdkWHpEbVg5SndoMEZaVlUKm0Z7YJZxUb1y0riV8XpvaLYWo8N2Lenk
            sPOHKoDJD5jovf+aIQYE0kVihrn6/XRd5pUIcya0TA7nCXMpVlGNUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:51:16Z"
    mac: ENC[AES256_GCM,data:D0mOB0oE6OLLE9j03x9Y+M6ikF/pPUcn+GPYZZt/WzBdxGR+B8QGZtXT7hHT15cwbShYlhtsVvj9EfI328lcKkFSc39cqfWZoBEP4JE4sUb23aiOS7S0Br/AceQZuAPGnwoZ06RnBlvIPfsi50O5Py9xB4XEJN3sQpzHBWjYpKY=,iv:Nng9dKQxulJg5VmakMPdkz2JGypmr2GpLGG0sP0Ftbw=,tag:fVKGz1Pc5zvXQZJ/+S2I4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
