apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
stringData:
    password: ENC[AES256_GCM,data:nb8pvOd6lKxGGG2A6MfRD+nCamqZElIYEKs3rPtmI14gWlYAEYWTsQvXZ0LMs91a2bWEzAE0KTBYpFto0kTL5kqe,iv:FKaZSytl1O6ZEVcq90h9WVK1dFdCRgd17JbDVzPFoRs=,tag:C1oSulVsF/KkXzRgtl4yPA==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTXNmdzdxVHZBQjdSMk1X
            a0p1MlhkYnBhMVFVTWJEZk1DYldzZEtlNVVVCkRIVUN2QkFFQlRLdUhaem5ZclRS
            ZTRxbm1STXBKVmtCYVFXL3IvdUtKejgKLS0tIG8yWS81L0NWeDM2amxNUnduRU43
            dlNrZEJkUERyOFhNZzFUaGNFeU5IQTAKHid4n2aGnsjPu5TvE+zPZSsyqj7CIrNc
            3AOozsVWIQk+nN5m7+vkCD67ggIuIJxQn07bILu2xOXnnp4HaGf/yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:21:14Z"
    mac: ENC[AES256_GCM,data:xjhoSUKLgHre/guSpakT+y2C0o6/VFtf9edSN+kjqdjytQozHifvCvf/tLDgSW3QH/uyvPrTGYJKoH4SxBP6einUUO4LLF897cJck9lU+XhcRYDTFdvL4Jm4wcFXH2tQyFj/IE2MJtOjrGjKEC/oDkUhKvcB9PR1yTu4fhQinzk=,iv:jUFtO8dTg5NGapIUKKen8joAeu02RnF7PBb6mKuEL+o=,tag:PoljvuDC7bmMB9QuwVlR1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
