---
- name: Determine available groups
  ansible.builtin.getent:
    database: group

# Remove default users that should not exist on managed nodes
- name: Remove unwanted users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
    force: true
  loop: "{{ common_users_absent | default([]) }}"
  loop_control:
    label: "{{ item }}"

# Create User and Group

- name: Realize Groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.uid }}"
  loop: "{{ common_users | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Realize Users and set Groups
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    groups: "{{ item.groups | default([]) | intersect(ansible_facts.getent_group) }}"
    shell: /bin/bash
    password: "{{ item.password | default('!') }}"
  loop: "{{ common_users | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Realize Authorized Keys for users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item['keys'] | authorized_builder(pubkey_directory) }}"
    state: present
    exclusive: true
  loop: "{{ common_users | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set Primary Group of Homedirs (in case gids changed)
  ansible.builtin.file:
    dest: /home/{{ item.name }}
    group: "{{ item.name }}"
  loop: "{{ common_users | default([]) }}"
  loop_control:
    label: /home/{{ item.name }}
  when: not ansible_check_mode
