# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
    namespace: forgejo
type: Opaque
stringData:
    PASSWD: ENC[AES256_GCM,data:BOMxeFtk7fnu9M0a5wgAN1aKfKOnNwCnAUyrzylPAEm1GtCh0lBvND4TpIg=,iv:PFxBg+oXkELp0QTeVx0IWymbEHCO5ml+OcxEc7smCbs=,tag:ysrXEBU6w2cPfjQ0wpKcSQ==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZTEwemlTOXZ1eUdyeU1q
            VVExR2kvZHFiQ0k2eTc2M0V0YXVjVURYT1M4CnhjMXRiQUFvaGlLbGJGd3R3ejc0
            MEV3ZkduT1hyampRcEJKVldhSDdxdXcKLS0tIGNBNStFalU0dVRKVzhsQWl4Y0Fp
            ZTFnUmllUzBuYzdTYUZEakhabEFOUkkK+geoCQWTAQGtI2+cU5G8KiAEkvkeCYtu
            soLx2XVqd9k4KmD+APOPJA5K64w9wU5nKMmTXlBDGfSB8UqmueSn/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T17:40:39Z"
    mac: ENC[AES256_GCM,data:d8+YHkuGumdX0+QwQq2pWSpZLr3bcNaEhfM1wCtyJALmPwsvuFlJ+hFZ1QS/lgW2tM0zZV3Qcz+KX8vyX7RvJ+wtRUQzTDuQ7a7KAE0Gpz5nbo8yuJBXELU9VxCF4Yoxkc59j3I+v1Rt7QoPEEC3uEJYF3zFMEKdtDNZZn0Z/ec=,iv:Oz/L2dHmiuxMEDjbrE9Z+HdKCZi65uGN8SuA7tjCr20=,tag:1tbt+SkkIt38F3HumDeD4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
