# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ztIGAbv9z0SLT6FcMA==,iv:Xm5LEyZ+nlTrX4sSV1iGvYkUxOQS+L1s4SZizvlrFuM=,tag:w2ikLkcmp3nx88cRvPVrlg==,type:str]
    password: ENC[AES256_GCM,data:XA0d8YoxIyUCzascUG80NULG6TQptlWjn14SP45LaZYhJcj3JrwyM/WB2YY=,iv:ZmQfsGkq2HK9set3kqMpal14tl6TI4aowEtxKZ6IdwA=,tag:2S1lUtWeH3WshlV2CxQGMw==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWjFQeHZaOVgxckJrTWlV
            S0ZiSVlZUHJCYXZTOGo1dmUzd092UHI0VUE4CkdwYkxWNTJuRk9mYm1yczgwTG1J
            TlNMOXNOelpRQm9JTW9id2lKYkRJVncKLS0tIEsvUTBCcHAyT2dtNlhNYXFKbEVm
            UFlKMjR5YVdqRkg4eW1Seks1cmJobkEKgK0w8qfYMQZRKVWIrC/bEMTnVX6yAfeP
            AoRfpRJN+nhL2bj/qdkHXgFDoNUb8DiVbqOFXznCObiX7smTA9sT+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:01:55Z"
    mac: ENC[AES256_GCM,data:44AX6SL9wJ7q5qgorspq6d2u14Qgv6LPD/ro5DHbUnxDGONJPBDw4KXtYqq9Ppcx2vaSrRb1HUHm7H79TTD8uJxL/D2teQ6FkBoDZAIyiMUeBDX0OfZQb2qKHnTVgvkmMbPbUwiNZzO+GMw4U3kPuc0Ca3HtGUnmGY64lIeUn5k=,iv:gi3t+XILyVsBH3jWkAR3lH3z6QWZQ1u4pB7fFOAO7vE=,tag:yZfz7m7T9LNBZ97elx0N8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
