# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oauth-secret
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:T8jtIOc9Vg==,iv:UyR3tk8jwsiNhu3Ljaedd8JzvdKcy4n+KbmSkqUC4Oo=,tag:n8n4wFz+L0Ip1Mei9mKwiw==,type:str]
    secret: ENC[AES256_GCM,data:haWFXYF77pIzVIP5e11ITAi6RvUyIcKlC3djdVk/oG44d/VYSQEe0HEqDRDFsmPKAtyGdHBOAzOuSD2CYOIWuQ==,iv:mDsYYiX1Wz1xZZcOzuIc7QSiynknd9xvBmDke+3WHTY=,tag:TVSToiMjgcAfh/tioXuQBg==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYjZyQkRzSEtMRXB3M3NL
            RnNTc2srU0phMXdXMmo2bFlNQWJEUXA4NFhFCjRIakFZK0c3Q1JFVXNLdVY0VmRD
            ZmxSdzZyRmpKWXA1bnZKRnFlYnlSMG8KLS0tIExQTVMwc2tFZ244dk81L3NSOElS
            NlJUcERYRHh2cUg4WjU2RGtwOHFUUHMKIbknwYNLa/NCn/J5hen+JYO4iyd5T6R/
            3631myw0wSm4srumzW4iKmrTxr27d8l+jmoc/gxK3T6YDH95IEkkyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:05:19Z"
    mac: ENC[AES256_GCM,data:TELmdXuaz5bfXd+V8xWfhj2bFRX+EPuuSOvWvtmDzwrUr4Zz52c2duPkoiLePqgQ8oBhYZeGtjg6LXmXLlshayrXkJlkvs+LO62n/wEzamgho3JVgodF55IDlOhJGihjJOdaZGY+ablLaiz3D0eG8s6Y7TQBJdzwXZIcN7pk4Ow=,iv:Re5PI9G0Aq1dxvc3dMG9tQxpNFdQFnYw2QOLUGbF3SU=,tag:9qW5BuAJb3YRv2t4e074sQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
