# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
    namespace: forgejo
type: Opaque
stringData:
    DB_TYPE: ENC[AES256_GCM,data:6qFPU0Lndp8=,iv:jaT8oJAMtgEKd4yWOcbYAB/bx95Tc5OL5PaQd22NEFo=,tag:SMMz7BM/BCoFq80BbwKFYQ==,type:str]
    HOST: ENC[AES256_GCM,data:D0sKxQHoN98OyYIYp5x2CzTA/juoy3E=,iv:gOn+s3NvjczZC/V5+BIQZPMFvwDrH9kLU9VMlIuALKs=,tag:u+8PWZSJAaPqUfw48HVXwQ==,type:str]
    NAME: ENC[AES256_GCM,data:dt6n5EG/gg==,iv:DFU9CVQ65c9/X00K1oAqg5WKBM4syXmkt0Ha1A+E2ZE=,tag:Gu4b6AVc5m3AOqo+6i8Rpw==,type:str]
    USER: ENC[AES256_GCM,data:+ceZ122aow==,iv:QNAF58l7QH4l/k4QjN1+a7MTom8VRYhj/7Y7FJ3uWPE=,tag:rhrnwTCvEPZc59WnARbnzg==,type:str]
    PASSWD: ENC[AES256_GCM,data:LiKPrR3cSw/+4mQ+uLH99VwyIQALrrVznBbg5K+QwlPUP/YqIGY8/jafjk8=,iv:ETrnik75ofDYRNx26+mNUcKf19GFdX512ae6wm7iU5s=,tag:Nk/091RAbZM287UyyixKUQ==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ3ZzNzdJQWJveUQxVHNE
            VDV1WDdENFVIQkw2cTMrRWtWYW1uNVh0Q0FvCnZ2a1ozMDZ2L2QzSXBwQVRiOU0z
            OG5ZT2pnQ2wvYnVzbUZuQjdzblJOZWcKLS0tIEFXSDlKeE1kWTZxTDE3endnWWxk
            Y0xSS2FVNHcyR1dyZ3pzV3IvYm5vemsKvNEk5hm4N9cdHoD0pqPVo/NfZ7cfStbB
            AvlyzUk2mHDZh8PYi5zHuC5abn4aOBk+rydOHPNO44DbydIXeQRbLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:45:08Z"
    mac: ENC[AES256_GCM,data:f5mg3NqaCNuCZ1Lfkjf5AstbBtfq61FW6+DN7zH3ikdgoKuxxwLntlAU2P/KkJPdcE3hsPsaqXeBy1mLe3XGMmgIz2WySWr1TB7ajzm0hqtnQerOcULG8TU5VJ1vGu7fd/45NTda3OWNQsPBA4u0DBc+9pG0/Py0ZVcRMNaesQg=,iv:PMIKh99BZFgRwpJczb6oScrGUBfnvnwR1bndvbFe6Lk=,tag:Mc1+D2zaCoySAcgvL2Pr+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
