# TEMPLATE — fill in users + argon2 password hashes, then encrypt with:
#   sops -e -i k8s/infrastructure/controllers/authelia/users-database.yaml
# Generate password hashes via:
#   docker run --rm authelia/authelia:latest \
#     authelia crypto hash generate argon2 --password '<your password>'
# Once encrypted, uncomment the entry in this directory's kustomization.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-database
    namespace: authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:rvF4OFZqxPuzRd/TY6n87TYQHbnTcQbB7+bg6RL2tKlryXA+GXNc6ItYU1UDB9254OHPasPUkM2arXv5xRrKvZzv8eMHirlzyOJIEeqY/eJAbMlSlqzHy+FwN4EoUsAKCThK6N2T4nCgHwooi91lo1czUzr6z1GFBQQ8LBoNFcGKZIuTQfaoHHcfEbxdlMJiaQKIpV+YRgiaoxULl3I9YbqIfHsDu5s8DHwR7Tz16zjvGCk3H2gWqpWMGuSnm3J7Q/ehru08pBG2xEJUS2oCEcgWPQob390xmqFJPrk96dkuHakgCKOEeymlUC0XTi+yRjDHjwKElq9HVZ0kqhorXQP4Z6/nvRJkvu8MTc3ftIF23UzlieWwAVI6VU5YB6GEytr3WPUDjz1/vpF8mVVYlCCb8spyCejf5Ysmzid7ZWXTjYkK1oiqbfTfceALCTlVZyDTP1dm8FfWkVfyfOHahQ4dRDeejdxIQObeNgTgYJzshf9nZSFiaXtFoE7MfXeDm/aIkC6pIsnMpiOSC2rT1zKToCmvgesDWYL1FEW5qXoGsAfYCryg/JQo6vYEZyBiwgK/U39mlhrn7TF0ZWEySyRK/2crtaixivT860o=,iv:X9aoBT96Tik94KHnfgAXr66DO91N1AYNHmSpejXnTLg=,tag:gN6JWNCzZng/v8jUVlr8ZQ==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWUtqS2ptb01jdWRBY1VG
            em1EeWVlZHpPdnNqSk1uSWllSTJ5TWFSQjFVCjlpTm0rSm1oTmNQaXNQblNaNzMy
            ZTBiUWFzdjZXZVB6c2xGZmVlUkFoNmsKLS0tIGwrMitUN1lCVThFT2hUYkEyQ3JS
            K0lBanprQ1cyYmtSNEpVWmJFdG5aSlUKyZt2H0sFr7F09QIBYeZVktW6fEbxdY8x
            09gSz38Hs/RS0wnVTfh2hctCWtVpdBOTeVn2IHVE3XAHuaxE1lQr/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T21:09:08Z"
    mac: ENC[AES256_GCM,data:LXAyEim0sX44+Oya+Okh1M3rhR920XJEvILLotaWAczZ6JUwoH8fwCYmPcWyi5nVDZIqOry8RqDHsYLG2bC1KutdQzWSBIb4cBzlNM5kmwFZmYuDO3EobxDixdMhdfh+jX9guzK5BGrLkkg6codImJPKU1NBRlCF9Btlng4N48c=,iv:AF6nAZQj1EzrAQi91qQYn47cDvjts37RRnQ/gRufQKI=,tag:yR9Cpq+Z7Es4xFo060/ShA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
