apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflared
stringData:
  token: ENC[AES256_GCM,data:VAaKGsIWhkOwrKYJsRdXhmW82vrPfwn6nslsVL6pQ2wksgMINj+PyrGReCqxtiwzDRYwnjVqoDv9p5EIFgTiUenjAx+Q0ucsVqq0fNng0KFQcs/02WIx7tUW3K27BvauZ4XlhYZ24FwqH616crEVYCKs//w64msQIqk2IBrNBBP+RATICV0BUlP/wsqo4r8chmBAPEVCJvRorols9kPmMR3FYPW72CA/xfwWfq7LiKM1Wvdpcd27QA==,iv:HhdVax1p41G3r3LLB0HhLOUJpeEVMCR5dNq7VJF//gM=,tag:umx+tRBs9K2xizwhnKdy1w==,type:str]
sops:
  age:
    - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVXVHWkZ5d0pEZGkwWnFC
        RDdTR3VBQXJiV1dKOFN4MTE3R2M3bTVMdUVjCnorYndWWE9tN0JPY2Z0TGFUS1Ay
        UUg2TE0weGZUUytRVldNWVpUSWxtNncKLS0tIDgxWnVLUVE5NEswa2ZBbDMvRGlp
        YXVRUVlzeVoxQVUzQmVRMFV2M0thajgKmatLnNnWHsFBpeF/tgXOZJq4ArhvMXtl
        ghmhCzsaB0avzgXDVDZwGk2dlM+KzDMjAqLcfSiWsrgQhjJNAW/GZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T16:01:47Z"
  mac: ENC[AES256_GCM,data:d0y8v1JbUcmtO7Gk/ZChOt1kPTTVGJ7mYT6s8IVPQTjQIXx9mCv33Go+ieI/BwB41KBYak35VR/bjZ1tr/Zc5PJ28VHSnN1qTyorm4JBaEH2FpRKfpxIeqbjl0g7Nb9pEEmhfrB/9rhgo6bIbPju7jV/lDoIq/j5uz3iYIYk4iw=,iv:Pka/VtIMA+8UCsf5IaWeNbOHGY8W78T+qetqTTnf+W0=,tag:Z5SYYp8VUfRn8szIgZE5xA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
