all:
  vars:
    ansible_user: ansible
  children:
    k3s_server:
      hosts:
        jellypi:
          ansible_host: "192.168.0.17"
    k3s_agent:
      hosts:
        cherrypi:
          ansible_host: "192.168.0.212"
