apiVersion: v1
kind: Secret
metadata:
    name: ghost-credentials
    namespace: ghost
stringData:
    values.yaml: ENC[AES256_GCM,data:hmRwuc9JR2k7P6at+EvltBDIk2GD+n6Qjbj5tk/GZK6cLpVLJXM/zZ9v8wwcHOrci3W+QldacGeW1VOTK93Dg0v6ZssoaekbfwJMfGzMurUZeg1Pj+VM1ytZgCn+m5+Iqo6U3558VgA/X4j+DmvS1vK5usLZbCqsQ4YGucboItehJYr0hT3zoDqismQ9ESlkXQx/54oZfVgDlaj8eD7GhG51BHWgErU0RFxDutLukZFjmdYrU6kCy/OFJR2CNoEo4gWFxp9QxrGKfc/4TmYJ7RHLvt7xjLDoYCeZJ9ILYLuIgVWtsg==,iv:gwSuQgonk7YIRoNegNWLUtKzQc62TenVP/Hbsbk2/HA=,tag:zexQ38qzbYq1nVL+DaqRhA==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRajdYRW5IMzJjRnJ5QThG
            NHRGeTExeHhzbmU0SlptRXFuZlA0bWtIN3gwCkxhWHBZeGFxVTQ5QUVvcGNBbkxC
            ZXR5aE5ZZnN4RXFpSU5YZEtoekMxYlUKLS0tIGtDelEvUjBnSGFQM3lHaUgxcU5W
            VVJPUlA1cFQyTGJuN0lIK0Z6cWkySFUKXo8fthG42r5dXXDd5M7xtaKjLz6LR5TD
            AiWKhl3TGDnwLbBVk2q5od26QCpfEsAPi/+216mEaHVPnjfoirN4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T12:38:01Z"
    mac: ENC[AES256_GCM,data:I3LCXH0z6dY8aIyh+7etohSoJ9SSR8pgAchNN3HlzmfgRyrg1kILJ3zuVvM0rQAh3KaCi5sx/1yHuClFyJsmADmm3htp2YZBpZlkvCvIXwoDg/8VP5ztaB6dMVP39CL0BupGjeYA/9JzbRITlwju+NpEOFTTOTUaJrVVfpmJZ+c=,iv:yKJBgEyx6maakhwoRy8U1AxcnntaDn+tDw85erwYcnU=,tag:8nnh4f1lMRJBEr1A15Jg3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
