apiVersion: v1
kind: Secret
metadata:
    name: ghost-mariadb-credentials
    namespace: ghost
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:VK27cIvOjiWjnV/wgLVe0iRj5razsabzgk3qBFepOtcMcZanxdFFsfD1oLZCytdnsW3zDWAUW23cYXyOacqlxI8Arg0GVw0Q8STOqnyCi2a9Gu9cRbzEeg==,iv:/3rciH0PCRYGEa/Y4hiwhabypcRB9FEKSnIU2xAbr2Q=,tag:hI9gZMsoG5F9DPLE5zYpmQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:T1kV0yOS47AYuvYxH9QmTrFNw+Qv0ssg5bteGQjRnmpMah87LC5MTPdUjv9QS8An+LVMPpHPpXwChoxvFE11zoFrk4KEax9ZyneCWcRa/6qhO2PMGR1L0g==,iv:CHrcAmZ08Iw+htn2CiNcoH+Jivgs+KKHsspHuF2MV6o=,tag:1xPwCRqIDfdybvs5b+H4kQ==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdzY2NFR6UFRKNytDVDkw
            UjN1VnBsRE9WYWx6Rk56NlE4eC8xa3F4ZGhrCko0OENmYjEySXZ4bGoyRFd1Qm9N
            Nmh1ek9LZ2NBS1MybmlOL3MyVjlpdUEKLS0tIDVHdEUraGhmOUJiYWlvQXFMSk5M
            K1hDWE0yMzI1bDN4enF2RENFa3JLSm8KLOuNavpwoUc+Bqb1i0nCNZsc/B2nOwyY
            GS3zVz94BRLBUZLbfvcFu2FwhwlSdyDNwETOCKrxgS3i7/OLnEOJYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T15:25:53Z"
    mac: ENC[AES256_GCM,data:DQE65KE4OmMKrG+Cf+KMaKkNvcBlglBtFLaxsp9Z/THoiXRUgWzUx5ToupFXfRpJBjyyNG3jFg1MjcA7O0D5ezwYY1CjVep2RXccal9JCSeOM3SnqgWEG/r7HvDejbMsYqjeAGJ+5v95HrMXVECTcdUTCgrgfq+Mt5Hd2KXDAg4=,iv:o9bQMbVdIXaBIv9Uay9mM4ibaH1uyjTxdsUEzup7COA=,tag:paLjQJg3lVgffkxki8gP9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
