apiVersion: v1
kind: Secret
metadata:
    name: ghost-credentials
    namespace: ghost
stringData:
    ghost-password: ENC[AES256_GCM,data:TV+vHpXsm2Yn7Pt7V/x67JH2kV5ZcPOzSWAsRuvk2hqyFIgFE8kaofOw3i+IdIXXqvcfUl+SIZrJDfEeYz2wYhN9U6M=,iv:rhxV/pdHDLKkZHAbQknspGuIxgGO+vhGNOOgNNJwLhI=,tag:sqVu/QtNHxOmbWgpK0Ht1w==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUEcxMEZPbGlMYWYvRXU1
            K0tWU3ROeEVSazNGM3BDbXVDN3Q0UWpRbmlnClk3aDJRNllTV0NDSHVQcWpuV1Yy
            eHNZZVNYUEZVcTFoVHpmaUt5M0JTYUkKLS0tICtTdnFnaWdKaHphK3NyZTRueUg2
            b3NCeHVOU1RPdE5LTmxUekx6T1pBQWcKmTt1aS6qc0MbEYbNi+I+EdKq7TnGkwcH
            X3nuu4fN9WIzV+OY4lGEeEOvr6QKXURZZ0QD/A7Xq1RS8uTdFVFhYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T15:25:42Z"
    mac: ENC[AES256_GCM,data:XoinvilfdnPrBlnI9RmqK87+lonvEEQBH2kag8JQppOVw9l/7c5HVs3PUzj74UflTltaS/LXP/la3nY4756Z5koMwR1T3gAIgzjJKk2g5+TfJIlMtlcT7+nB3/xnNi8+kUQGyjzyivssbZ/nvhE8/tta5DdKrWQPrAk4egowR0w=,iv:PR0bFoZ9SVGlQQuJl4wS+drzKGun7c+RVpwUw0fUovs=,tag:oaxknuHxtgoS4nG1wvho6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
