apiVersion: v1
kind: Secret
metadata:
    name: ghost-mariadb-credentials
    namespace: ghost
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:TzXWya49ujMG+DbIi12iF92K0m/ruzFZDcxXjlcj1bpe76zKqsDlxgzpQxqfEGG2j9GgcT7OHDVsU5XoyRZuNzYuYsBEFlXWECwVS/q61DqD+ejBidccGg==,iv:pUt0xO86fYJFAg7MHoBMG3OJw92hNHCFdnGbp8o4tCM=,tag:gt3Q1RH2CsirIZQ0vmLP/g==,type:str]
    mariadb-password: ENC[AES256_GCM,data:alfFaYQc+27C4uCH1Lh//dP7Bxu1a5JWCrbGpLQQVlicppDu/9MWs1cclgvnyHMVKCBe8d3bTTioTfvP4yCDyLe6z/Jro5VH0myG0R5c5seVy/T6N5cMcQ==,iv:lS2ll8ew418qdri8kiGNQGmxI0kv6JmVWPcwWD+WUO0=,tag:qduT5m7ujN9zwspiSQKIHQ==,type:str]
    values.yaml: ENC[AES256_GCM,data:fLipRoqH8lWEFIv4fir925mXsb5oZy4ePn+KSPsoMZtxifP/YjRuS643tW6tlNZ/c6ocGqS0Pd4Fwkkyyuz56ZnmSRJQB1vbiBYP9E9xx58BkrtHYz5fmNyzDAp8y2vJa607LIZHtkJswPBG/XrgMpGGHo5XRkRpFdNadw==,iv:Nw7OY/c3wVxQ7U99sYmlRw96HFL6faaAk8Qs6V1Iaqk=,tag:DPb4U87wiEbqbD5OskanCA==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldzJ2WFVEVnVJb2Z1bnZa
            cW1IbU5BTXNDakJZaTA2VG1SN2VIbXZqREhzCnV1TnowNDhpMWF1SEkrU0lsa0NX
            WDZaeTdxM0twSVpuNzJuVnpwUmdSbFUKLS0tIDJsQkJVZ0U0T2xKcFBGVlZsUmxH
            QWJSSmhGR0ptQWp2VHIwejVaWVA2U00KmGwsV4fmvCDuyda+6P9NMhKtmbeXemaa
            RUccbJTuYHgXY7ngyUaIXpyXjysp+/n7oZxIJAMthcUPpLJwByFR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:13:59Z"
    mac: ENC[AES256_GCM,data:n7JOm18Q2fGfLjaC85VzD1I/p0uiWpj2k9Qma3/vtwdwl3Vsd1+3na+zbiLJLi1dg/w+QE7mKB5eddzrCI2FHqkFhheJiQThK94+3YqYBzuNA9OnJlNcWP2hU6C/tVLz+bggsjuef++NZU8NxT3/y0yID0GMH/OAIFH7B8ZnMR0=,iv:H7RodllJAz+q4YDuJ4LLB1LjZ6GMr7ueIVOFiLMRZFo=,tag:wvWpZhdzghYZJq8y28KjQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
