apiVersion: v1
kind: Secret
metadata:
    name: ghost-credentials
    namespace: ghost
stringData:
    values.yaml: ENC[AES256_GCM,data:shk8lHMc2eqkjTF7HMmdy3r7yP1ykdvzde7tL2PVf7exzmtI+CsThwYOhDN+yL6GdcsrSBECrm/8PvSINLPjWMrB7Or1c2sgoPbDMqZ2KxITNoqBDVLcpYfi0d3yiXuiu5LCZpZ5HUTo9c5u6obxBkiqpGmuvW9G/CiLO8iVeay7rsgx6L4zCIuv/eMPtqa58XTKWdltswrSzLOTi0EIbeYQsvEqAeNnPfLfkSjfa0bItqh5g5d8/jlszQeeg+KTsQd/Uwynhse2N8GZcSpuafmqq39aprmWJq4hDSMCP0iHX4QRgV6afTa2k+MWJvOK1C7NluNN6dxglJB9PxzSTd1nlZLT2Q45KzeWhXt3tPFjWgjb8yBfLrPMyIw6jT0pbRkeWpkqaiCWaIx5qS/V92JUYgukKs0=,iv:0lUEcfQYO9kffottaiGAA6tpbAtOlqkYaBUh9/G8xuE=,tag:jWjnU4F//nzwHdm5A7M7Tg==,type:str]
sops:
    age:
        - recipient: age14utxu3kn6vtq62pljd3xt0klc77pkqdxmuw8y9u5j239xlmjlamsdystyv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aU44RFR2aWxaOUs3Ky9H
            TEQ2ckxMUFVQY2d6b21JVVdDMEFvMjVOd2s0Cm02S0NUUGQ5MElvRHhrK1ZLcW1Z
            OFl6R05TZ3lDOWVrK1JadHl6bjd5NmMKLS0tIElTWjlDMG5sZ1hZY2l1TjFQeWs5
            UlhyaHE4bUxIN3doK0lkbGhqRVhUZXcKCgZhhjw8S4iAVt1BqtpMX9z7yJwbsyLU
            Ro6HEYYfl7HAY1SjvjyWrmN9b+iCJUBbe1a55GTvf4zV+X+HAwpozQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T16:47:35Z"
    mac: ENC[AES256_GCM,data:Bti+46U7HHKimd0U64ATrads/jR2GoxHrdU8vxErbfYwRt1GwgYfxCbMURl3Snx5feuNAREkAVc2CjnRfJK6cSVlsHMSQCJ4RyNUTU/OlNyUf2ytJdRB5O3fTdlKvY5+mjFHZWN3Fbverhhg2IsSTxC38+D6Bu1EVOI52V6wj3Q=,iv:XUiAaATkWeo6NzkoD3K6TFXDyYFaoT8lqzCmwVcH1n8=,tag:vLKwW9RfPdRTiZvDBCZYLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
