# TODO: add forwardauth-authelia + authelia-https-headers middlewares once Ghost admin
# protection via Authelia is desired (see ADR-011 for middleware names and namespaces)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost
  namespace: ghost
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`scrimreaper.dev`)
      services:
        - kind: Service
          name: ghost-ghost-on-kubernetes-service
          port: 2368
