apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost
  namespace: ghost
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`scrimreaper.dev`)
      services:
        - kind: Service
          name: ghost
          port: 80
